# Portable release packaging for Live2DRecovery (AGENT.5.3).
#
# Requires: cargo, python (only for generating synthetic canvas-sized PNGs).
# Produces dist/Live2DRecovery-<version>-win-x64/ plus a zip.
param(
    [string]$Version = "0.1.0-alpha"
)

$ErrorActionPreference = "Stop"
$root = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$distRoot = Join-Path $root "dist"
$package = Join-Path $distRoot "Live2DRecovery-$Version-win-x64"
$acceptance = Join-Path $package "acceptance"
$samples = Join-Path $package "samples"
$licenses = Join-Path $package "LICENSES"

if (Test-Path $package) { Remove-Item -Recurse -Force $package }
New-Item -ItemType Directory -Force -Path $package, $acceptance, $samples, $licenses | Out-Null

Write-Output "building release binary..."
Push-Location $root
try {
    cargo build --release -p recovery-cli | Out-Host
} finally {
    Pop-Location
}
$exe = Join-Path $root "target\release\recovery.exe"
$distExe = Join-Path $package "Live2DRecovery.exe"
Copy-Item $exe $distExe

# Synthetic canvas-sized PNG generator (no third-party assets are used).
$pngScript = Join-Path $env:TEMP "l2d-package-png.py"
@'
import struct, sys, zlib
def chunk(kind, data):
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)
def solid(width, height, rgba):
    raw = b"".join(b"\x00" + bytes(rgba) * width for _ in range(height))
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", zlib.compress(raw, 1)) + chunk(b"IEND", b"")
open(sys.argv[3], "wb").write(solid(int(sys.argv[1]), int(sys.argv[2]), (90, 150, 210, 255)))
'@ | Set-Content -Encoding UTF8 $pngScript

$cases = @(
    @{ Name = "01-minimal"; Fixture = "fixture-002-artmesh-param.moc3"; Note = "1 Part + 1 ArtMesh + 1 texture + 2-key parameter" },
    @{ Name = "02-deformer"; Fixture = "hierarchy-005-warp-rotation-artmesh.moc3"; Note = "Part -> Warp -> Rotation -> ArtMesh" },
    @{ Name = "03-keyform"; Fixture = "keyform-002-1d-three-keys.moc3"; Note = "1 parameter with 3 keys and keyed part/art-mesh forms" }
)

foreach ($case in $cases) {
    $sampleDir = Join-Path $samples $case.Name
    New-Item -ItemType Directory -Force -Path (Join-Path $sampleDir "textures") | Out-Null
    $fixture = Join-Path $root "fixtures\synthetic\$($case.Fixture)"
    Copy-Item $fixture (Join-Path $sampleDir "model.moc3")
    & python $pngScript 800 600 (Join-Path $sampleDir "textures\page0.png") | Out-Null
    @"
Live2DRecovery synthetic sample: $($case.Name)
$($case.Note)

Run:
  Live2DRecovery.exe recover model.moc3 --textures textures --output recovered.cmo3

Generated by the project itself; no third-party model data is included.
"@ | Set-Content -Encoding UTF8 (Join-Path $sampleDir "README.txt")

    $cmo3 = Join-Path $acceptance "$($case.Name).cmo3"
    & $distExe recover $fixture --textures (Join-Path $sampleDir "textures") --output $cmo3 --report (Join-Path $acceptance "$($case.Name).report.json") | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "recover failed for $($case.Name)" }

    $precheck = & $distExe inspect-cmo3 $cmo3 --json | ConvertFrom-Json
    if (-not $precheck.caff.valid -or $precheck.xml.dangling_refs -ne 0 -or $precheck.xml.duplicate_ids -ne 0) {
        throw "structural precheck failed for $($case.Name)"
    }
    $expected = Join-Path $acceptance "expected"
    New-Item -ItemType Directory -Force -Path $expected | Out-Null
    $precheck | ConvertTo-Json -Depth 6 | Set-Content -Encoding UTF8 (Join-Path $expected "$($case.Name).inspection.json")
    Write-Output "acceptance $($case.Name): structural PASS"
}

@'
# Cubism Acceptance Checklist (0.1.0-alpha)

Editor version: NOT RECORDED (Cubism Editor not available in the build
environment; acceptance: NOT EXECUTED).

Structural precheck (inspect-cmo3) already PASSED for all three files;
see expected/*.inspection.json.

## 01-minimal.cmo3
[ ] opens without repair/recovery dialog
[ ] texture visible, correct orientation, not black
[ ] art mesh visible
[ ] no fatal warnings

## 02-deformer.cmo3
[ ] opens; Part -> Warp -> Rotation -> ArtMesh hierarchy visible
[ ] geometry visible under the deformers

## 03-keyform.cmo3
[ ] opens; parameter visible with 3 keys
[ ] moving the parameter moves the keyed forms (min/default/max)

## Save/reopen (each file)
[ ] Save As -> Close -> Reopen the saved file succeeds

Record exact editor version, OS and date here when executed.
Structural PASS is NOT a Cubism compatibility claim.
'@ | Set-Content -Encoding UTF8 (Join-Path $acceptance "ACCEPTANCE_CHECKLIST.md")

@'
Live2DRecovery 0.1.0-alpha (EXPERIMENTAL, portable Windows build)

What this is
  A command line tool that reads a Live2D .moc3 runtime file (plus its
  textures) and writes a .cmo3 editor project reconstructed from the data
  that is actually stored in the file.

Alpha warning
  This build is EXPERIMENTAL. Real-world compatibility has not been
  validated; only synthetic fixtures and structural checks have been run.
  Cubism Editor validation is NOT TESTED.

Supported input
  .moc3 (Live2D Cubism runtime file), optional model3.json for texture
  paths, and the referenced PNG textures.

Basic commands
  Live2DRecovery.exe self-test
  Live2DRecovery.exe recover model.moc3 --textures textures --output recovered.cmo3
  Live2DRecovery.exe inspect model.moc3
  Live2DRecovery.exe inspect-cmo3 recovered.cmo3 --json

Output
  recovered.cmo3 and recovered.report.json (recovery report).

Structural validation vs Cubism validation
  Structural validation checks the generated file against the documented
  container/XML structure and reference integrity. It is reported as
  PASS/NOT TESTED separately and is NOT a claim that Cubism Editor will
  open or accept the project.

Known limitations
  - Cubism Editor open/save/reopen: NOT TESTED
  - draw-order groups, glue target schema and offscreen surfaces are not
    serialized (recorded in the report)
  - the layered image is synthetic (one canvas-sized layer per textured
    mesh), never a recovered PSD
  - overwriting an existing output requires --force

Rights notice
  Use only with Live2D assets that you own or have permission to analyze
  or recover. Do not use this tool to bypass licensing or DRM.
'@ | Set-Content -Encoding UTF8 (Join-Path $package "README.txt")

@'
Third-party notices for the Live2DRecovery 0.1.0-alpha portable build.

This package contains only the project's own code and synthetic assets.
No external research implementation (moc2cmo, Stretchy Studio, py-moc3,
Quadrism, caff-archive) is bundled, linked or required at runtime; those
projects were used for format research only.

Rust dependencies (statically linked, permissive licenses):
  clap            MIT OR Apache-2.0   https://github.com/clap-rs/clap
  env_logger      MIT OR Apache-2.0   https://github.com/rust-cli/env_logger
  log             MIT OR Apache-2.0   https://github.com/rust-lang/log
  serde           MIT OR Apache-2.0   https://github.com/serde-rs/serde
  serde_json      MIT OR Apache-2.0   https://github.com/serde-rs/json
  windows-sys     MIT OR Apache-2.0   (transitive via env_logger)

Full license texts are available from the linked repositories; the
project itself ships no vendored dependency sources.
'@ | Set-Content -Encoding UTF8 (Join-Path $package "THIRD_PARTY_NOTICES.txt")

@'
Third-party license summary (see ../THIRD_PARTY_NOTICES.txt).

All bundled code is the project's own (no license declared yet; project
decision pending). Static Rust dependencies are MIT OR Apache-2.0.
'@ | Set-Content -Encoding UTF8 (Join-Path $licenses "THIRD_PARTY_LICENSES.md")

$hashLines = @()
$hashLines += "SHA256 Live2DRecovery.exe  $((Get-FileHash $distExe -Algorithm SHA256).Hash.ToLower())"
foreach ($case in $cases) {
    $cmo3 = Join-Path $acceptance "$($case.Name).cmo3"
    $hashLines += "SHA256 acceptance/$($case.Name).cmo3  $((Get-FileHash $cmo3 -Algorithm SHA256).Hash.ToLower())"
}
$hashLines | Set-Content -Encoding ASCII (Join-Path $package "checksums.txt")

$zip = Join-Path $distRoot "Live2DRecovery-$Version-win-x64.zip"
if (Test-Path $zip) { Remove-Item -Force $zip }
Compress-Archive -Path $package -DestinationPath $zip
Write-Output "package: $package"
Write-Output "zip:     $zip"
Get-Content (Join-Path $package "checksums.txt")
