//! Deterministic synthetic MOC3 fixture generator (master spec section 20).
//!
//! This module produces *test fixtures only*: it never touches `.cmo3` and is
//! not part of the recovery pipeline. It writes minimal, well-formed MOC3
//! files following the documented layout so the inspector can be exercised
//! without using any third-party model data.
//!
//! Every generated byte stream is a pure function of the fixture definition
//! and the chosen format version. Identifiers use a `Synthetic` prefix so the
//! data can never be confused with a real model.

#![forbid(unsafe_code)]
#![deny(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use moc3_ingest::counts::CountInfo;
use moc3_ingest::table::{self, Elem};
use moc3_ingest::MocVersion;

/// A generated fixture: name and bytes.
#[derive(Debug, Clone)]
pub struct Fixture {
    /// File name, e.g. `fixture-001-single-artmesh.moc3`.
    pub name: &'static str,
    /// Complete file bytes.
    pub bytes: Vec<u8>,
}

/// Canvas properties of a synthetic model.
#[derive(Debug, Clone)]
pub struct CanvasSpec {
    /// Pixels per unit.
    pub pixels_per_unit: f32,
    /// Canvas X origin.
    pub origin_x: f32,
    /// Canvas Y origin.
    pub origin_y: f32,
    /// Canvas width.
    pub width: f32,
    /// Canvas height.
    pub height: f32,
    /// Y axis reversed flag.
    pub y_reversed: bool,
}

impl Default for CanvasSpec {
    fn default() -> Self {
        Self {
            pixels_per_unit: 1000.0,
            origin_x: 400.0,
            origin_y: 300.0,
            width: 800.0,
            height: 600.0,
            y_reversed: false,
        }
    }
}

/// Parameter definition (one key table per parameter).
#[derive(Debug, Clone)]
pub struct ParamSpec {
    /// Identifier.
    pub name: String,
    /// Minimum value.
    pub min: f32,
    /// Maximum value.
    pub max: f32,
    /// Default value.
    pub default: f32,
    /// Repeat flag.
    pub repeat: bool,
    /// Decimal places.
    pub decimals: i32,
    /// Key values.
    pub keys: Vec<f32>,
}

impl ParamSpec {
    /// Two-key angle style parameter.
    pub fn two_key(name: &str) -> Self {
        Self {
            name: name.to_string(),
            min: -30.0,
            max: 30.0,
            default: 0.0,
            repeat: false,
            decimals: 2,
            keys: vec![-30.0, 30.0],
        }
    }
}

/// Keyform binding: a set of key table indices.
#[derive(Debug, Clone)]
pub struct BindingSpec {
    /// Key table indices.
    pub tables: Vec<usize>,
}

/// Part definition.
#[derive(Debug, Clone)]
pub struct PartSpec {
    /// Identifier.
    pub name: String,
    /// Parent part.
    pub parent: Option<usize>,
    /// Binding index.
    pub binding: usize,
    /// Visible flag.
    pub visible: bool,
    /// Enabled flag.
    pub enabled: bool,
}

/// Deformer kind.
#[derive(Debug, Clone)]
pub enum DeformerKind {
    /// Warp deformer with a `(rows + 1) x (cols + 1)` grid.
    Warp {
        /// Grid rows.
        rows: u32,
        /// Grid columns.
        cols: u32,
        /// Quad transform flag.
        quad: bool,
    },
    /// Rotation deformer.
    Rotation {
        /// Base angle.
        base_angle: f32,
    },
}

/// Deformer definition.
#[derive(Debug, Clone)]
pub struct DeformerSpec {
    /// Identifier.
    pub name: String,
    /// Kind and kind-specific data.
    pub kind: DeformerKind,
    /// Parent part.
    pub parent_part: Option<usize>,
    /// Parent deformer.
    pub parent_deformer: Option<usize>,
    /// Binding index.
    pub binding: usize,
}

/// Art mesh definition (a quad by default).
#[derive(Debug, Clone)]
pub struct ArtMeshSpec {
    /// Identifier.
    pub name: String,
    /// Parent part.
    pub parent_part: Option<usize>,
    /// Parent deformer.
    pub parent_deformer: Option<usize>,
    /// Texture page number.
    pub texture: u32,
    /// Binding index.
    pub binding: usize,
    /// Masking art mesh indices.
    pub masks: Vec<i32>,
    /// Raw drawable flag byte.
    pub flags: u8,
    /// Quad corner positions (CCW).
    pub quad: [(f32, f32); 4],
    /// Quad UVs.
    pub uv: [(f32, f32); 4],
}

impl ArtMeshSpec {
    /// Quad mesh with the given identifier.
    pub fn quad(name: &str, binding: usize) -> Self {
        Self {
            name: name.to_string(),
            parent_part: None,
            parent_deformer: None,
            texture: 0,
            binding,
            masks: Vec::new(),
            flags: 0,
            quad: [(0.0, 0.0), (100.0, 0.0), (100.0, 100.0), (0.0, 100.0)],
            uv: [(0.1, 0.1), (0.9, 0.1), (0.9, 0.9), (0.1, 0.9)],
        }
    }
}

/// Glue definition connecting two art meshes.
#[derive(Debug, Clone)]
pub struct GlueSpec {
    /// Identifier.
    pub name: String,
    /// First glued art mesh index.
    pub art_mesh_a: usize,
    /// Second glued art mesh index.
    pub art_mesh_b: usize,
    /// Binding index.
    pub binding: usize,
    /// Flat `(weight, position_index)` entries in source order.
    pub info: Vec<(f32, u16)>,
}

/// Draw order group definition.
#[derive(Debug, Clone)]
pub struct DrawGroupSpec {
    /// Items as `(type, index, self_group)` where type 0 = art mesh, 1 = part.
    pub items: Vec<(i64, i64, i64)>,
    /// Maximum draw order.
    pub max_order: i32,
    /// Minimum draw order.
    pub min_order: i32,
}

/// A complete synthetic model description.
#[derive(Debug, Clone, Default)]
pub struct SyntheticModel {
    /// MOC3 version byte.
    pub version: u8,
    /// Canvas info.
    pub canvas: CanvasSpec,
    /// Parameters.
    pub parameters: Vec<ParamSpec>,
    /// Bindings.
    pub bindings: Vec<BindingSpec>,
    /// Parts.
    pub parts: Vec<PartSpec>,
    /// Deformers.
    pub deformers: Vec<DeformerSpec>,
    /// Art meshes.
    pub art_meshes: Vec<ArtMeshSpec>,
    /// Glue entries.
    pub glues: Vec<GlueSpec>,
    /// Draw order groups.
    pub draw_groups: Vec<DrawGroupSpec>,
}

fn align8(value: usize) -> usize {
    (value + 7) & !7usize
}

fn id_bytes(name: &str) -> Vec<u8> {
    let raw = name.as_bytes();
    assert!(raw.len() < 64, "fixture identifier too long: {name}");
    let mut out = vec![0u8; 64];
    out[..raw.len()].copy_from_slice(raw);
    out
}

fn f32_bytes(values: &[f32]) -> Vec<u8> {
    let mut out = Vec::with_capacity(values.len() * 4);
    for value in values {
        out.extend_from_slice(&value.to_le_bytes());
    }
    out
}

fn i32_bytes(values: &[i32]) -> Vec<u8> {
    let mut out = Vec::with_capacity(values.len() * 4);
    for value in values {
        out.extend_from_slice(&value.to_le_bytes());
    }
    out
}

fn u16_bytes(values: &[u16]) -> Vec<u8> {
    let mut out = Vec::with_capacity(values.len() * 2);
    for value in values {
        out.extend_from_slice(&value.to_le_bytes());
    }
    out
}

fn u8_bytes(values: &[u8]) -> Vec<u8> {
    values.to_vec()
}

struct Arrays {
    param_ids: Vec<u8>,
    param_max: Vec<f32>,
    param_min: Vec<f32>,
    param_default: Vec<f32>,
    param_repeat: Vec<i32>,
    param_decimals: Vec<i32>,
    param_kt_begin: Vec<i32>,
    param_kt_count: Vec<i32>,
    param_type: Vec<i32>,
    param_blend_begin: Vec<i32>,
    param_blend_count: Vec<i32>,
    param_ext_begin: Vec<i32>,
    param_ext_count: Vec<i32>,

    key_table_begin: Vec<i32>,
    key_table_count: Vec<i32>,
    key_values: Vec<f32>,

    key_table_index: Vec<i32>,
    binding_begin: Vec<i32>,
    binding_count: Vec<i32>,

    part_ids: Vec<u8>,
    part_binding: Vec<i32>,
    part_kf_begin: Vec<i32>,
    part_kf_count: Vec<i32>,
    part_visible: Vec<i32>,
    part_enabled: Vec<i32>,
    part_parent: Vec<i32>,
    part_offscreen: Vec<i32>,
    part_kf_draw_order: Vec<f32>,

    deformer_ids: Vec<u8>,
    deformer_binding: Vec<i32>,
    deformer_visible: Vec<i32>,
    deformer_enabled: Vec<i32>,
    deformer_parent_part: Vec<i32>,
    deformer_parent_deformer: Vec<i32>,
    deformer_type: Vec<i32>,
    deformer_local_index: Vec<i32>,

    warp_binding: Vec<i32>,
    warp_kf_begin: Vec<i32>,
    warp_kf_count: Vec<i32>,
    warp_vertex_count: Vec<i32>,
    warp_rows: Vec<i32>,
    warp_cols: Vec<i32>,
    warp_quad: Vec<i32>,
    warp_kf_opacity: Vec<f32>,
    warp_kf_pos_begin: Vec<i32>,
    warp_kf_color_begin: Vec<i32>,
    warp_kf_mul_begin: Vec<i32>,
    warp_kf_scr_begin: Vec<i32>,

    rotation_binding: Vec<i32>,
    rotation_kf_begin: Vec<i32>,
    rotation_kf_count: Vec<i32>,
    rotation_base_angle: Vec<f32>,
    rotation_kf_opacity: Vec<f32>,
    rotation_kf_angle: Vec<f32>,
    rotation_kf_origin_x: Vec<f32>,
    rotation_kf_origin_y: Vec<f32>,
    rotation_kf_scale: Vec<f32>,
    rotation_kf_reflect_x: Vec<i32>,
    rotation_kf_reflect_y: Vec<i32>,
    rotation_kf_color_begin: Vec<i32>,
    rotation_kf_mul_begin: Vec<i32>,
    rotation_kf_scr_begin: Vec<i32>,

    art_mesh_ids: Vec<u8>,
    art_mesh_binding: Vec<i32>,
    art_mesh_kf_begin: Vec<i32>,
    art_mesh_kf_count: Vec<i32>,
    art_mesh_visible: Vec<i32>,
    art_mesh_enabled: Vec<i32>,
    art_mesh_parent_part: Vec<i32>,
    art_mesh_parent_deformer: Vec<i32>,
    art_mesh_texture: Vec<i32>,
    art_mesh_flags: Vec<u8>,
    art_mesh_vertex_count: Vec<i32>,
    art_mesh_uv_begin: Vec<i32>,
    art_mesh_index_begin: Vec<i32>,
    art_mesh_index_count: Vec<i32>,
    art_mesh_mask_begin: Vec<i32>,
    art_mesh_mask_count: Vec<i32>,
    art_mesh_kf_opacity: Vec<f32>,
    art_mesh_kf_draw_order: Vec<f32>,
    art_mesh_kf_pos_begin: Vec<i32>,
    art_mesh_kf_color_begin: Vec<i32>,
    art_mesh_kf_mul_begin: Vec<i32>,
    art_mesh_kf_scr_begin: Vec<i32>,
    art_mesh_blend_mode: Vec<i32>,

    keyform_positions: Vec<f32>,
    uv_values: Vec<f32>,
    indices: Vec<u16>,
    mask_values: Vec<i32>,

    draw_group_obj_begin: Vec<i32>,
    draw_group_obj_count: Vec<i32>,
    draw_group_obj_total: Vec<i32>,
    draw_group_max: Vec<i32>,
    draw_group_min: Vec<i32>,
    draw_item_type: Vec<i32>,
    draw_item_index: Vec<i32>,
    draw_item_self_group: Vec<i32>,

    keyform_mul_colors: Vec<f32>,
    keyform_scr_colors: Vec<f32>,

    glue_ids: Vec<u8>,
    glue_binding: Vec<i32>,
    glue_kf_begin: Vec<i32>,
    glue_kf_count: Vec<i32>,
    glue_mesh_a: Vec<i32>,
    glue_mesh_b: Vec<i32>,
    glue_info_begin: Vec<i32>,
    glue_info_count: Vec<i32>,
    glue_info_weight: Vec<f32>,
    glue_info_position_index: Vec<u16>,
    glue_keyform_intensity: Vec<f32>,

    canvas: Vec<u8>,
    counts: CountInfo,
}

fn make_count_info() -> CountInfo {
    CountInfo {
        parts: 0,
        deformers: 0,
        warp_deformers: 0,
        rotation_deformers: 0,
        art_meshes: 0,
        parameters: 0,
        part_keyforms: 0,
        warp_deformer_keyforms: 0,
        rotation_deformer_keyforms: 0,
        art_mesh_keyforms: 0,
        keyform_positions: 0,
        parameter_binding_indices: 0,
        keyform_bindings: 0,
        parameter_bindings: 0,
        keys: 0,
        uvs: 0,
        position_indices: 0,
        drawable_masks: 0,
        draw_order_groups: 0,
        draw_order_group_objects: 0,
        glue: 0,
        glue_info: 0,
        glue_keyforms: 0,
        keyform_multiply_colors: 0,
        keyform_screen_colors: 0,
        blend_shape_parameter_bindings: 0,
        blend_shape_keyform_bindings: 0,
        blend_shapes_warp_deformers: 0,
        blend_shapes_art_meshes: 0,
        blend_shape_constraint_indices: 0,
        blend_shape_constraints: 0,
        blend_shape_constraint_values: 0,
        blend_shapes_parts: 0,
        blend_shapes_rotation_deformers: 0,
        blend_shapes_glue: 0,
        offscreens: 0,
        offscreen_keyforms: 0,
        blend_shapes_offscreens: 0,
        unknown_nonzero: Vec::new(),
        raw_int_count: 0,
    }
}

/// Build the complete file bytes for a synthetic model.
pub fn build(model: &SyntheticModel) -> Vec<u8> {
    // Developer error only: fixture definitions always use valid versions.
    // Returning empty bytes makes the mistake visible in tests instead of
    // panicking.
    let version = match MocVersion::from_byte(model.version) {
        Some(version) => version,
        None => return Vec::new(),
    };
    let mut arrays = populate(model, version);
    arrays.counts.raw_int_count = version.count_info_ints();
    assemble(&arrays, version)
}

fn populate(model: &SyntheticModel, version: MocVersion) -> Arrays {
    let mut arrays = Arrays {
        param_ids: Vec::new(),
        param_max: Vec::new(),
        param_min: Vec::new(),
        param_default: Vec::new(),
        param_repeat: Vec::new(),
        param_decimals: Vec::new(),
        param_kt_begin: Vec::new(),
        param_kt_count: Vec::new(),
        param_type: Vec::new(),
        param_blend_begin: Vec::new(),
        param_blend_count: Vec::new(),
        param_ext_begin: Vec::new(),
        param_ext_count: Vec::new(),
        key_table_begin: Vec::new(),
        key_table_count: Vec::new(),
        key_values: Vec::new(),
        key_table_index: Vec::new(),
        binding_begin: Vec::new(),
        binding_count: Vec::new(),
        part_ids: Vec::new(),
        part_binding: Vec::new(),
        part_kf_begin: Vec::new(),
        part_kf_count: Vec::new(),
        part_visible: Vec::new(),
        part_enabled: Vec::new(),
        part_parent: Vec::new(),
        part_offscreen: Vec::new(),
        part_kf_draw_order: Vec::new(),
        deformer_ids: Vec::new(),
        deformer_binding: Vec::new(),
        deformer_visible: Vec::new(),
        deformer_enabled: Vec::new(),
        deformer_parent_part: Vec::new(),
        deformer_parent_deformer: Vec::new(),
        deformer_type: Vec::new(),
        deformer_local_index: Vec::new(),
        warp_binding: Vec::new(),
        warp_kf_begin: Vec::new(),
        warp_kf_count: Vec::new(),
        warp_vertex_count: Vec::new(),
        warp_rows: Vec::new(),
        warp_cols: Vec::new(),
        warp_quad: Vec::new(),
        warp_kf_opacity: Vec::new(),
        warp_kf_pos_begin: Vec::new(),
        warp_kf_color_begin: Vec::new(),
        warp_kf_mul_begin: Vec::new(),
        warp_kf_scr_begin: Vec::new(),
        rotation_binding: Vec::new(),
        rotation_kf_begin: Vec::new(),
        rotation_kf_count: Vec::new(),
        rotation_base_angle: Vec::new(),
        rotation_kf_opacity: Vec::new(),
        rotation_kf_angle: Vec::new(),
        rotation_kf_origin_x: Vec::new(),
        rotation_kf_origin_y: Vec::new(),
        rotation_kf_scale: Vec::new(),
        rotation_kf_reflect_x: Vec::new(),
        rotation_kf_reflect_y: Vec::new(),
        rotation_kf_color_begin: Vec::new(),
        rotation_kf_mul_begin: Vec::new(),
        rotation_kf_scr_begin: Vec::new(),
        art_mesh_ids: Vec::new(),
        art_mesh_binding: Vec::new(),
        art_mesh_kf_begin: Vec::new(),
        art_mesh_kf_count: Vec::new(),
        art_mesh_visible: Vec::new(),
        art_mesh_enabled: Vec::new(),
        art_mesh_parent_part: Vec::new(),
        art_mesh_parent_deformer: Vec::new(),
        art_mesh_texture: Vec::new(),
        art_mesh_flags: Vec::new(),
        art_mesh_vertex_count: Vec::new(),
        art_mesh_uv_begin: Vec::new(),
        art_mesh_index_begin: Vec::new(),
        art_mesh_index_count: Vec::new(),
        art_mesh_mask_begin: Vec::new(),
        art_mesh_mask_count: Vec::new(),
        art_mesh_kf_opacity: Vec::new(),
        art_mesh_kf_draw_order: Vec::new(),
        art_mesh_kf_pos_begin: Vec::new(),
        art_mesh_kf_color_begin: Vec::new(),
        art_mesh_kf_mul_begin: Vec::new(),
        art_mesh_kf_scr_begin: Vec::new(),
        art_mesh_blend_mode: Vec::new(),
        keyform_positions: Vec::new(),
        uv_values: Vec::new(),
        indices: Vec::new(),
        mask_values: Vec::new(),
        draw_group_obj_begin: Vec::new(),
        draw_group_obj_count: Vec::new(),
        draw_group_obj_total: Vec::new(),
        draw_group_max: Vec::new(),
        draw_group_min: Vec::new(),
        draw_item_type: Vec::new(),
        draw_item_index: Vec::new(),
        draw_item_self_group: Vec::new(),
        keyform_mul_colors: Vec::new(),
        keyform_scr_colors: Vec::new(),
        glue_ids: Vec::new(),
        glue_binding: Vec::new(),
        glue_kf_begin: Vec::new(),
        glue_kf_count: Vec::new(),
        glue_mesh_a: Vec::new(),
        glue_mesh_b: Vec::new(),
        glue_info_begin: Vec::new(),
        glue_info_count: Vec::new(),
        glue_info_weight: Vec::new(),
        glue_info_position_index: Vec::new(),
        glue_keyform_intensity: Vec::new(),
        canvas: Vec::new(),
        counts: make_count_info(),
    };

    // ---- parameters and key tables --------------------------------------
    let mut table_keys: Vec<usize> = Vec::new();
    for parameter in &model.parameters {
        arrays
            .param_ids
            .extend_from_slice(&id_bytes(&parameter.name));
        arrays.param_max.push(parameter.max);
        arrays.param_min.push(parameter.min);
        arrays.param_default.push(parameter.default);
        arrays
            .param_repeat
            .push(if parameter.repeat { 1 } else { 0 });
        arrays.param_decimals.push(parameter.decimals);
        arrays
            .param_kt_begin
            .push(i32::try_from(arrays.key_table_begin.len()).unwrap_or(0));
        arrays.param_kt_count.push(1);
        arrays.param_type.push(0);
        arrays.param_blend_begin.push(0);
        arrays.param_blend_count.push(0);
        arrays.param_ext_begin.push(0);
        arrays.param_ext_count.push(0);

        arrays
            .key_table_begin
            .push(i32::try_from(arrays.key_values.len()).unwrap_or(0));
        arrays
            .key_table_count
            .push(i32::try_from(parameter.keys.len()).unwrap_or(0));
        arrays.key_values.extend_from_slice(&parameter.keys);
        table_keys.push(parameter.keys.len());
    }

    // ---- bindings --------------------------------------------------------
    let mut bindings = model.bindings.clone();
    if bindings.is_empty() {
        bindings.push(BindingSpec { tables: Vec::new() });
    }
    for binding in &bindings {
        for table in &binding.tables {
            assert!(
                *table < table_keys.len(),
                "binding references unknown key table"
            );
            arrays
                .key_table_index
                .push(i32::try_from(*table).unwrap_or(0));
        }
        arrays
            .binding_begin
            .push(i32::try_from(arrays.key_table_index.len() - binding.tables.len()).unwrap_or(0));
        arrays
            .binding_count
            .push(i32::try_from(binding.tables.len()).unwrap_or(0));
    }

    let kf_product = |binding: usize| -> i64 {
        let mut product: i64 = 1;
        if let Some(spec) = bindings.get(binding) {
            for table in &spec.tables {
                if let Some(count) = table_keys.get(*table) {
                    if *count > 1 {
                        product = product.saturating_mul(*count as i64);
                    }
                }
            }
        }
        product.max(1)
    };

    // ---- parts -----------------------------------------------------------
    let mut part_kf_cursor = 0i32;
    for part in &model.parts {
        let keyforms = kf_product(part.binding);
        arrays.part_ids.extend_from_slice(&id_bytes(&part.name));
        arrays
            .part_binding
            .push(i32::try_from(part.binding).unwrap_or(0));
        arrays.part_kf_begin.push(part_kf_cursor);
        arrays
            .part_kf_count
            .push(i32::try_from(keyforms).unwrap_or(1));
        arrays.part_visible.push(if part.visible { 1 } else { 0 });
        arrays.part_enabled.push(if part.enabled { 1 } else { 0 });
        arrays.part_parent.push(
            part.parent
                .map(|value| i32::try_from(value).unwrap_or(-1))
                .unwrap_or(-1),
        );
        arrays.part_offscreen.push(-1);
        for slot in 0..keyforms {
            arrays
                .part_kf_draw_order
                .push(f32::from(i16::try_from(slot).unwrap_or(0)));
        }
        part_kf_cursor += i32::try_from(keyforms).unwrap_or(1);
    }
    arrays.counts.part_keyforms = u32::try_from(part_kf_cursor).unwrap_or(0);

    // ---- deformers -------------------------------------------------------
    let mut warp_kf_cursor = 0i32;
    let mut rotation_kf_cursor = 0i32;
    let mut local_warp: usize = 0;
    let mut local_rotation: usize = 0;
    for deformer in &model.deformers {
        let keyforms = kf_product(deformer.binding);
        arrays
            .deformer_ids
            .extend_from_slice(&id_bytes(&deformer.name));
        arrays
            .deformer_binding
            .push(i32::try_from(deformer.binding).unwrap_or(0));
        arrays.deformer_visible.push(1);
        arrays.deformer_enabled.push(1);
        arrays.deformer_parent_part.push(
            deformer
                .parent_part
                .map(|value| i32::try_from(value).unwrap_or(-1))
                .unwrap_or(-1),
        );
        arrays.deformer_parent_deformer.push(
            deformer
                .parent_deformer
                .map(|value| i32::try_from(value).unwrap_or(-1))
                .unwrap_or(-1),
        );

        match &deformer.kind {
            DeformerKind::Warp { rows, cols, quad } => {
                arrays.deformer_type.push(0);
                arrays
                    .deformer_local_index
                    .push(i32::try_from(local_warp).unwrap_or(0));
                local_warp += 1;
                arrays
                    .warp_binding
                    .push(i32::try_from(deformer.binding).unwrap_or(0));
                arrays.warp_kf_begin.push(warp_kf_cursor);
                arrays
                    .warp_kf_count
                    .push(i32::try_from(keyforms).unwrap_or(1));
                let vertex_count = (rows + 1).saturating_mul(cols + 1);
                arrays
                    .warp_vertex_count
                    .push(i32::try_from(vertex_count).unwrap_or(0));
                arrays.warp_rows.push(i32::try_from(*rows).unwrap_or(0));
                arrays.warp_cols.push(i32::try_from(*cols).unwrap_or(0));
                arrays.warp_quad.push(if *quad { 1 } else { 0 });
                let color_begin = i32::try_from(arrays.keyform_mul_colors.len() / 3).unwrap_or(0);
                for keyform in 0..keyforms {
                    arrays.warp_kf_opacity.push(1.0);
                    arrays
                        .warp_kf_pos_begin
                        .push(i32::try_from(arrays.keyform_positions.len()).unwrap_or(0));
                    for row in 0..=*rows {
                        for column in 0..=*cols {
                            let jitter = f32::from(i16::try_from(keyform).unwrap_or(0)) * 0.5;
                            arrays
                                .keyform_positions
                                .push(column as f32 * 100.0 + jitter);
                            arrays.keyform_positions.push(row as f32 * 100.0);
                        }
                    }
                    arrays
                        .warp_kf_mul_begin
                        .push(color_begin + i32::try_from(keyform).unwrap_or(0));
                    arrays
                        .warp_kf_scr_begin
                        .push(color_begin + i32::try_from(keyform).unwrap_or(0));
                    arrays
                        .keyform_mul_colors
                        .extend_from_slice(&[1.0, 1.0, 1.0]);
                    arrays
                        .keyform_scr_colors
                        .extend_from_slice(&[0.0, 0.0, 0.0]);
                }
                arrays.warp_kf_color_begin.push(color_begin);
                warp_kf_cursor += i32::try_from(keyforms).unwrap_or(1);
            }
            DeformerKind::Rotation { base_angle } => {
                arrays.deformer_type.push(1);
                arrays
                    .deformer_local_index
                    .push(i32::try_from(local_rotation).unwrap_or(0));
                local_rotation += 1;
                arrays
                    .rotation_binding
                    .push(i32::try_from(deformer.binding).unwrap_or(0));
                arrays.rotation_kf_begin.push(rotation_kf_cursor);
                arrays
                    .rotation_kf_count
                    .push(i32::try_from(keyforms).unwrap_or(1));
                arrays.rotation_base_angle.push(*base_angle);
                let color_begin = i32::try_from(arrays.keyform_mul_colors.len() / 3).unwrap_or(0);
                for keyform in 0..keyforms {
                    let offset = f32::from(i16::try_from(keyform).unwrap_or(0)) * 2.0;
                    arrays.rotation_kf_opacity.push(1.0);
                    arrays.rotation_kf_angle.push(*base_angle + offset);
                    arrays.rotation_kf_origin_x.push(50.0);
                    arrays.rotation_kf_origin_y.push(50.0);
                    arrays.rotation_kf_scale.push(1.0);
                    arrays.rotation_kf_reflect_x.push(0);
                    arrays.rotation_kf_reflect_y.push(0);
                    arrays
                        .rotation_kf_mul_begin
                        .push(color_begin + i32::try_from(keyform).unwrap_or(0));
                    arrays
                        .rotation_kf_scr_begin
                        .push(color_begin + i32::try_from(keyform).unwrap_or(0));
                    arrays
                        .keyform_mul_colors
                        .extend_from_slice(&[1.0, 1.0, 1.0]);
                    arrays
                        .keyform_scr_colors
                        .extend_from_slice(&[0.0, 0.0, 0.0]);
                }
                arrays.rotation_kf_color_begin.push(color_begin);
                rotation_kf_cursor += i32::try_from(keyforms).unwrap_or(1);
            }
        }
    }
    arrays.counts.warp_deformer_keyforms = u32::try_from(warp_kf_cursor).unwrap_or(0);
    arrays.counts.rotation_deformer_keyforms = u32::try_from(rotation_kf_cursor).unwrap_or(0);

    // ---- art meshes ------------------------------------------------------
    let mut art_kf_cursor = 0i32;
    for mesh in &model.art_meshes {
        let keyforms = kf_product(mesh.binding);
        arrays.art_mesh_ids.extend_from_slice(&id_bytes(&mesh.name));
        arrays
            .art_mesh_binding
            .push(i32::try_from(mesh.binding).unwrap_or(0));
        arrays.art_mesh_kf_begin.push(art_kf_cursor);
        arrays
            .art_mesh_kf_count
            .push(i32::try_from(keyforms).unwrap_or(1));
        arrays.art_mesh_visible.push(1);
        arrays.art_mesh_enabled.push(1);
        arrays.art_mesh_parent_part.push(
            mesh.parent_part
                .map(|value| i32::try_from(value).unwrap_or(-1))
                .unwrap_or(-1),
        );
        arrays.art_mesh_parent_deformer.push(
            mesh.parent_deformer
                .map(|value| i32::try_from(value).unwrap_or(-1))
                .unwrap_or(-1),
        );
        arrays
            .art_mesh_texture
            .push(i32::try_from(mesh.texture).unwrap_or(0));
        arrays.art_mesh_flags.push(mesh.flags);

        let vertex_count: i64 = 4;
        arrays
            .art_mesh_vertex_count
            .push(i32::try_from(vertex_count).unwrap_or(0));
        arrays
            .art_mesh_uv_begin
            .push(i32::try_from(arrays.uv_values.len()).unwrap_or(0));
        for (u, v) in &mesh.uv {
            arrays.uv_values.push(*u);
            arrays.uv_values.push(*v);
        }
        arrays
            .art_mesh_index_begin
            .push(i32::try_from(arrays.indices.len()).unwrap_or(0));
        let triangles: [[u16; 3]; 2] = [[0, 1, 2], [0, 2, 3]];
        arrays.art_mesh_index_count.push(6);
        for triangle in &triangles {
            arrays.indices.extend_from_slice(triangle);
        }
        arrays
            .art_mesh_mask_begin
            .push(i32::try_from(arrays.mask_values.len()).unwrap_or(0));
        arrays
            .art_mesh_mask_count
            .push(i32::try_from(mesh.masks.len()).unwrap_or(0));
        arrays.mask_values.extend_from_slice(&mesh.masks);

        let color_begin = i32::try_from(arrays.keyform_mul_colors.len() / 3).unwrap_or(0);
        for keyform in 0..keyforms {
            arrays.art_mesh_kf_opacity.push(1.0);
            arrays
                .art_mesh_kf_draw_order
                .push(f32::from(i16::try_from(keyform).unwrap_or(0)));
            arrays
                .art_mesh_kf_pos_begin
                .push(i32::try_from(arrays.keyform_positions.len()).unwrap_or(0));
            let jitter = f32::from(i16::try_from(keyform).unwrap_or(0)) * 2.0;
            for (x, y) in &mesh.quad {
                arrays.keyform_positions.push(*x + jitter);
                arrays.keyform_positions.push(*y);
            }
            arrays
                .art_mesh_kf_mul_begin
                .push(color_begin + i32::try_from(keyform).unwrap_or(0));
            arrays
                .art_mesh_kf_scr_begin
                .push(color_begin + i32::try_from(keyform).unwrap_or(0));
            arrays
                .keyform_mul_colors
                .extend_from_slice(&[1.0, 1.0, 1.0]);
            arrays
                .keyform_scr_colors
                .extend_from_slice(&[0.0, 0.0, 0.0]);
        }
        arrays.art_mesh_kf_color_begin.push(color_begin);
        arrays.art_mesh_blend_mode.push(0);
        art_kf_cursor += i32::try_from(keyforms).unwrap_or(1);
    }
    arrays.counts.art_mesh_keyforms = u32::try_from(art_kf_cursor).unwrap_or(0);

    // ---- glue -------------------------------------------------------------
    let mut glue_kf_cursor = 0i32;
    let mut glue_info_cursor = 0i32;
    for glue in &model.glues {
        let keyforms = kf_product(glue.binding);
        arrays.glue_ids.extend_from_slice(&id_bytes(&glue.name));
        arrays
            .glue_binding
            .push(i32::try_from(glue.binding).unwrap_or(0));
        arrays.glue_kf_begin.push(glue_kf_cursor);
        arrays
            .glue_kf_count
            .push(i32::try_from(keyforms).unwrap_or(1));
        arrays
            .glue_mesh_a
            .push(i32::try_from(glue.art_mesh_a).unwrap_or(0));
        arrays
            .glue_mesh_b
            .push(i32::try_from(glue.art_mesh_b).unwrap_or(0));
        arrays.glue_info_begin.push(glue_info_cursor);
        arrays
            .glue_info_count
            .push(i32::try_from(glue.info.len()).unwrap_or(0));
        for (weight, position_index) in &glue.info {
            arrays.glue_info_weight.push(*weight);
            arrays.glue_info_position_index.push(*position_index);
        }
        glue_info_cursor += i32::try_from(glue.info.len()).unwrap_or(0);
        for keyform in 0..keyforms {
            arrays
                .glue_keyform_intensity
                .push(1.0 + f32::from(i16::try_from(keyform).unwrap_or(0)) * 0.25);
        }
        glue_kf_cursor += i32::try_from(keyforms).unwrap_or(1);
    }
    arrays.counts.glue = u32::try_from(model.glues.len()).unwrap_or(0);
    arrays.counts.glue_info = u32::try_from(arrays.glue_info_weight.len()).unwrap_or(0);
    arrays.counts.glue_keyforms = u32::try_from(glue_kf_cursor).unwrap_or(0);

    // ---- draw groups -----------------------------------------------------
    for group in &model.draw_groups {
        arrays
            .draw_group_obj_begin
            .push(i32::try_from(arrays.draw_item_type.len()).unwrap_or(0));
        arrays
            .draw_group_obj_count
            .push(i32::try_from(group.items.len()).unwrap_or(0));
        arrays
            .draw_group_obj_total
            .push(i32::try_from(group.items.len()).unwrap_or(0));
        arrays.draw_group_max.push(group.max_order);
        arrays.draw_group_min.push(group.min_order);
        for (item_type, item_index, self_group) in &group.items {
            arrays
                .draw_item_type
                .push(i32::try_from(*item_type).unwrap_or(0));
            arrays
                .draw_item_index
                .push(i32::try_from(*item_index).unwrap_or(0));
            arrays
                .draw_item_self_group
                .push(i32::try_from(*self_group).unwrap_or(-1));
        }
    }

    // ---- counts ----------------------------------------------------------
    arrays.counts.parts = u32::try_from(model.parts.len()).unwrap_or(0);
    arrays.counts.deformers = u32::try_from(model.deformers.len()).unwrap_or(0);
    arrays.counts.warp_deformers = u32::try_from(local_warp).unwrap_or(0);
    arrays.counts.rotation_deformers = u32::try_from(local_rotation).unwrap_or(0);
    arrays.counts.art_meshes = u32::try_from(model.art_meshes.len()).unwrap_or(0);
    arrays.counts.parameters = u32::try_from(model.parameters.len()).unwrap_or(0);
    arrays.counts.keyform_positions = u32::try_from(arrays.keyform_positions.len()).unwrap_or(0);
    arrays.counts.parameter_binding_indices =
        u32::try_from(arrays.key_table_index.len()).unwrap_or(0);
    arrays.counts.keyform_bindings = u32::try_from(bindings.len()).unwrap_or(0);
    arrays.counts.parameter_bindings = u32::try_from(arrays.key_table_begin.len()).unwrap_or(0);
    arrays.counts.keys = u32::try_from(arrays.key_values.len()).unwrap_or(0);
    arrays.counts.uvs = u32::try_from(arrays.uv_values.len()).unwrap_or(0);
    arrays.counts.position_indices = u32::try_from(arrays.indices.len()).unwrap_or(0);
    arrays.counts.drawable_masks = u32::try_from(arrays.mask_values.len()).unwrap_or(0);
    arrays.counts.draw_order_groups = u32::try_from(model.draw_groups.len()).unwrap_or(0);
    arrays.counts.draw_order_group_objects =
        u32::try_from(arrays.draw_item_type.len()).unwrap_or(0);
    arrays.counts.keyform_multiply_colors =
        u32::try_from(arrays.keyform_mul_colors.len() / 3).unwrap_or(0);
    arrays.counts.keyform_screen_colors =
        u32::try_from(arrays.keyform_scr_colors.len() / 3).unwrap_or(0);

    arrays.canvas = {
        let mut bytes = Vec::with_capacity(24);
        bytes.extend_from_slice(&model.canvas.pixels_per_unit.to_le_bytes());
        bytes.extend_from_slice(&model.canvas.origin_x.to_le_bytes());
        bytes.extend_from_slice(&model.canvas.origin_y.to_le_bytes());
        bytes.extend_from_slice(&model.canvas.width.to_le_bytes());
        bytes.extend_from_slice(&model.canvas.height.to_le_bytes());
        bytes.push(if model.canvas.y_reversed { 1 } else { 0 });
        bytes.extend_from_slice(&[0u8, 0, 0]);
        bytes
    };

    let _ = version;
    arrays
}

fn assemble(arrays: &Arrays, version: MocVersion) -> Vec<u8> {
    let defs = table::defs_for(version);
    let slots = version.offset_slots();
    let table_end = 0x40 + slots * 4;

    let mut index_of: std::collections::BTreeMap<&'static str, usize> =
        std::collections::BTreeMap::new();
    for (index, def) in defs.iter().enumerate() {
        index_of.insert(def.name, index);
    }

    let mut content: Vec<Vec<u8>> = Vec::with_capacity(defs.len());
    for _ in 0..defs.len() {
        content.push(Vec::new());
    }

    let mut set = |name: &'static str, bytes: Vec<u8>| {
        let Some(index) = index_of.get(name).copied() else {
            assert!(
                index_of.contains_key(name),
                "section {name} absent in this version"
            );
            return;
        };
        if let Some(slot) = content.get_mut(index) {
            *slot = bytes;
        }
    };

    // Static sections.
    set("count_info", count_info_bytes(&arrays.counts, version));
    set("canvas_info", arrays.canvas.clone());

    // Parameters and key tables.
    set("parameter.id", arrays.param_ids.clone());
    set("parameter.maximum", f32_bytes(&arrays.param_max));
    set("parameter.minimum", f32_bytes(&arrays.param_min));
    set("parameter.default", f32_bytes(&arrays.param_default));
    set("parameter.repeat", i32_bytes(&arrays.param_repeat));
    set(
        "parameter.decimal_places",
        i32_bytes(&arrays.param_decimals),
    );
    set(
        "parameter.key_table_begin",
        i32_bytes(&arrays.param_kt_begin),
    );
    set(
        "parameter.key_table_count",
        i32_bytes(&arrays.param_kt_count),
    );
    if version.has_v42_sections() {
        set(
            "parameter.extension_key_begin",
            i32_bytes(&arrays.param_ext_begin),
        );
        set(
            "parameter.extension_key_count",
            i32_bytes(&arrays.param_ext_count),
        );
        set("parameter.type", i32_bytes(&arrays.param_type));
        set(
            "parameter.blend_key_table_begin",
            i32_bytes(&arrays.param_blend_begin),
        );
        set(
            "parameter.blend_key_table_count",
            i32_bytes(&arrays.param_blend_count),
        );
    }

    set("key_table_index", i32_bytes(&arrays.key_table_index));
    set("binding.key_table_begin", i32_bytes(&arrays.binding_begin));
    set("binding.key_table_count", i32_bytes(&arrays.binding_count));
    set("key_table.begin", i32_bytes(&arrays.key_table_begin));
    set("key_table.count", i32_bytes(&arrays.key_table_count));
    set("key.values", f32_bytes(&arrays.key_values));

    // Parts.
    set("part.id", arrays.part_ids.clone());
    set("part.binding_index", i32_bytes(&arrays.part_binding));
    set("part.keyform_begin", i32_bytes(&arrays.part_kf_begin));
    set("part.keyform_count", i32_bytes(&arrays.part_kf_count));
    set("part.visible", i32_bytes(&arrays.part_visible));
    set("part.enabled", i32_bytes(&arrays.part_enabled));
    set("part.parent_part", i32_bytes(&arrays.part_parent));
    if version.has_v53_sections() {
        set("part.offscreen_index", i32_bytes(&arrays.part_offscreen));
    }
    set(
        "part_keyform.draw_order",
        f32_bytes(&arrays.part_kf_draw_order),
    );
    if version.has_v53_sections() {
        let negatives: Vec<i32> = arrays.part_kf_draw_order.iter().map(|_| -1).collect();
        set("part_keyform.key_index", i32_bytes(&negatives));
    }

    // Deformers.
    set("deformer.id", arrays.deformer_ids.clone());
    set(
        "deformer.binding_index",
        i32_bytes(&arrays.deformer_binding),
    );
    set("deformer.visible", i32_bytes(&arrays.deformer_visible));
    set("deformer.enabled", i32_bytes(&arrays.deformer_enabled));
    set(
        "deformer.parent_part",
        i32_bytes(&arrays.deformer_parent_part),
    );
    set(
        "deformer.parent_deformer",
        i32_bytes(&arrays.deformer_parent_deformer),
    );
    set("deformer.type", i32_bytes(&arrays.deformer_type));
    set(
        "deformer.local_index",
        i32_bytes(&arrays.deformer_local_index),
    );

    set("warp.binding_index", i32_bytes(&arrays.warp_binding));
    set("warp.keyform_begin", i32_bytes(&arrays.warp_kf_begin));
    set("warp.keyform_count", i32_bytes(&arrays.warp_kf_count));
    set("warp.vertex_count", i32_bytes(&arrays.warp_vertex_count));
    set("warp.rows", i32_bytes(&arrays.warp_rows));
    set("warp.columns", i32_bytes(&arrays.warp_cols));
    if version.has_quad_transform() {
        set("warp.quad_transform", i32_bytes(&arrays.warp_quad));
    }
    if version.has_v42_sections() {
        set(
            "warp.keyform_color_begin",
            i32_bytes(&arrays.warp_kf_color_begin),
        );
    }
    set("warp_keyform.opacity", f32_bytes(&arrays.warp_kf_opacity));
    set(
        "warp_keyform.position_begin",
        i32_bytes(&arrays.warp_kf_pos_begin),
    );
    if version.has_v50_sections() {
        set(
            "warp_keyform.multiply_color_begin",
            i32_bytes(&arrays.warp_kf_mul_begin),
        );
        set(
            "warp_keyform.screen_color_begin",
            i32_bytes(&arrays.warp_kf_scr_begin),
        );
    }

    set(
        "rotation.binding_index",
        i32_bytes(&arrays.rotation_binding),
    );
    set(
        "rotation.keyform_begin",
        i32_bytes(&arrays.rotation_kf_begin),
    );
    set(
        "rotation.keyform_count",
        i32_bytes(&arrays.rotation_kf_count),
    );
    set(
        "rotation.base_angle",
        f32_bytes(&arrays.rotation_base_angle),
    );
    if version.has_v42_sections() {
        set(
            "rotation.keyform_color_begin",
            i32_bytes(&arrays.rotation_kf_color_begin),
        );
    }
    set(
        "rotation_keyform.opacity",
        f32_bytes(&arrays.rotation_kf_opacity),
    );
    set(
        "rotation_keyform.angle",
        f32_bytes(&arrays.rotation_kf_angle),
    );
    set(
        "rotation_keyform.origin_x",
        f32_bytes(&arrays.rotation_kf_origin_x),
    );
    set(
        "rotation_keyform.origin_y",
        f32_bytes(&arrays.rotation_kf_origin_y),
    );
    set(
        "rotation_keyform.scale",
        f32_bytes(&arrays.rotation_kf_scale),
    );
    set(
        "rotation_keyform.reflect_x",
        i32_bytes(&arrays.rotation_kf_reflect_x),
    );
    set(
        "rotation_keyform.reflect_y",
        i32_bytes(&arrays.rotation_kf_reflect_y),
    );
    if version.has_v50_sections() {
        set(
            "rotation_keyform.multiply_color_begin",
            i32_bytes(&arrays.rotation_kf_mul_begin),
        );
        set(
            "rotation_keyform.screen_color_begin",
            i32_bytes(&arrays.rotation_kf_scr_begin),
        );
    }

    // Art meshes.
    set("art_mesh.id", arrays.art_mesh_ids.clone());
    set(
        "art_mesh.binding_index",
        i32_bytes(&arrays.art_mesh_binding),
    );
    set(
        "art_mesh.keyform_begin",
        i32_bytes(&arrays.art_mesh_kf_begin),
    );
    set(
        "art_mesh.keyform_count",
        i32_bytes(&arrays.art_mesh_kf_count),
    );
    set("art_mesh.visible", i32_bytes(&arrays.art_mesh_visible));
    set("art_mesh.enabled", i32_bytes(&arrays.art_mesh_enabled));
    set(
        "art_mesh.parent_part",
        i32_bytes(&arrays.art_mesh_parent_part),
    );
    set(
        "art_mesh.parent_deformer",
        i32_bytes(&arrays.art_mesh_parent_deformer),
    );
    set(
        "art_mesh.texture_number",
        i32_bytes(&arrays.art_mesh_texture),
    );
    set("art_mesh.drawable_flags", u8_bytes(&arrays.art_mesh_flags));
    set(
        "art_mesh.vertex_count",
        i32_bytes(&arrays.art_mesh_vertex_count),
    );
    set("art_mesh.uv_begin", i32_bytes(&arrays.art_mesh_uv_begin));
    set(
        "art_mesh.index_begin",
        i32_bytes(&arrays.art_mesh_index_begin),
    );
    set(
        "art_mesh.index_count",
        i32_bytes(&arrays.art_mesh_index_count),
    );
    set(
        "art_mesh.mask_begin",
        i32_bytes(&arrays.art_mesh_mask_begin),
    );
    set(
        "art_mesh.mask_count",
        i32_bytes(&arrays.art_mesh_mask_count),
    );
    if version.has_v42_sections() {
        set(
            "art_mesh.keyform_color_begin",
            i32_bytes(&arrays.art_mesh_kf_color_begin),
        );
    }
    if version.has_v53_sections() {
        set(
            "art_mesh.blend_mode",
            i32_bytes(&arrays.art_mesh_blend_mode),
        );
    }
    set(
        "art_mesh_keyform.opacity",
        f32_bytes(&arrays.art_mesh_kf_opacity),
    );
    set(
        "art_mesh_keyform.draw_order",
        f32_bytes(&arrays.art_mesh_kf_draw_order),
    );
    set(
        "art_mesh_keyform.position_begin",
        i32_bytes(&arrays.art_mesh_kf_pos_begin),
    );
    if version.has_v50_sections() {
        set(
            "art_mesh_keyform.multiply_color_begin",
            i32_bytes(&arrays.art_mesh_kf_mul_begin),
        );
        set(
            "art_mesh_keyform.screen_color_begin",
            i32_bytes(&arrays.art_mesh_kf_scr_begin),
        );
    }

    // Geometry pools.
    set("keyform_position.xy", f32_bytes(&arrays.keyform_positions));
    set("uv.xy", f32_bytes(&arrays.uv_values));
    set("position_indices", u16_bytes(&arrays.indices));
    set("drawable_mask.indices", i32_bytes(&arrays.mask_values));

    // Draw order.
    set(
        "draw_group.object_begin",
        i32_bytes(&arrays.draw_group_obj_begin),
    );
    set(
        "draw_group.object_count",
        i32_bytes(&arrays.draw_group_obj_count),
    );
    set(
        "draw_group.object_total_count",
        i32_bytes(&arrays.draw_group_obj_total),
    );
    set("draw_group.max_order", i32_bytes(&arrays.draw_group_max));
    set("draw_group.min_order", i32_bytes(&arrays.draw_group_min));
    set("draw_item.type", i32_bytes(&arrays.draw_item_type));
    set("draw_item.index", i32_bytes(&arrays.draw_item_index));
    set(
        "draw_item.self_group",
        i32_bytes(&arrays.draw_item_self_group),
    );

    // Glue.
    set("glue.id", arrays.glue_ids.clone());
    set("glue.binding_index", i32_bytes(&arrays.glue_binding));
    set("glue.keyform_begin", i32_bytes(&arrays.glue_kf_begin));
    set("glue.keyform_count", i32_bytes(&arrays.glue_kf_count));
    set("glue.art_mesh_a", i32_bytes(&arrays.glue_mesh_a));
    set("glue.art_mesh_b", i32_bytes(&arrays.glue_mesh_b));
    set("glue.info_begin", i32_bytes(&arrays.glue_info_begin));
    set("glue.info_count", i32_bytes(&arrays.glue_info_count));
    set("glue_info.weight", f32_bytes(&arrays.glue_info_weight));
    set(
        "glue_info.position_index",
        u16_bytes(&arrays.glue_info_position_index),
    );
    set(
        "glue_keyform.intensity",
        f32_bytes(&arrays.glue_keyform_intensity),
    );

    if version.has_v42_sections() {
        let mut r = Vec::with_capacity(arrays.keyform_mul_colors.len() / 3);
        let mut g = Vec::with_capacity(r.capacity());
        let mut b = Vec::with_capacity(r.capacity());
        for entry in arrays.keyform_mul_colors.chunks_exact(3) {
            r.push(entry[0]);
            g.push(entry[1]);
            b.push(entry[2]);
        }
        set("keyform_color.multiply.r", f32_bytes(&r));
        set("keyform_color.multiply.g", f32_bytes(&g));
        set("keyform_color.multiply.b", f32_bytes(&b));
        let mut r = Vec::with_capacity(arrays.keyform_scr_colors.len() / 3);
        let mut g = Vec::with_capacity(r.capacity());
        let mut b = Vec::with_capacity(r.capacity());
        for entry in arrays.keyform_scr_colors.chunks_exact(3) {
            r.push(entry[0]);
            g.push(entry[1]);
            b.push(entry[2]);
        }
        set("keyform_color.screen.r", f32_bytes(&r));
        set("keyform_color.screen.g", f32_bytes(&g));
        set("keyform_color.screen.b", f32_bytes(&b));
    }

    // ---- layout ----------------------------------------------------------
    let mut file = vec![0u8; table_end];
    file[0..4].copy_from_slice(b"MOC3");
    if let Some(byte) = file.get_mut(4) {
        *byte = version.byte();
    }
    let mut offsets = vec![0u32; slots];
    for (index, def) in defs.iter().enumerate() {
        let count = table::count_for(def.count, &arrays.counts);
        let size = match def.elem {
            Elem::CountInfo => version.count_info_ints() as u64 * 4,
            other => other.size(version).saturating_mul(count),
        };
        let mut bytes = content.get(index).cloned().unwrap_or_default();
        if def.runtime {
            assert!(
                bytes.is_empty(),
                "runtime section {} should not have assigned content",
                def.name
            );
            bytes = vec![0u8; size as usize];
        }
        assert_eq!(
            bytes.len() as u64,
            size,
            "section {} size mismatch (expected {size} bytes)",
            def.name
        );
        let aligned = align8(file.len());
        file.resize(aligned, 0);
        if let Some(slot) = offsets.get_mut(index) {
            *slot = u32::try_from(file.len()).unwrap_or(0);
        }
        file.extend_from_slice(&bytes);
    }
    for (index, value) in offsets.iter().enumerate() {
        let at = 0x40 + index * 4;
        if let Some(slice) = file.get_mut(at..at + 4) {
            slice.copy_from_slice(&value.to_le_bytes());
        }
    }
    file
}

fn count_info_bytes(counts: &CountInfo, version: MocVersion) -> Vec<u8> {
    let named = [
        counts.parts,
        counts.deformers,
        counts.warp_deformers,
        counts.rotation_deformers,
        counts.art_meshes,
        counts.parameters,
        counts.part_keyforms,
        counts.warp_deformer_keyforms,
        counts.rotation_deformer_keyforms,
        counts.art_mesh_keyforms,
        counts.keyform_positions,
        counts.parameter_binding_indices,
        counts.keyform_bindings,
        counts.parameter_bindings,
        counts.keys,
        counts.uvs,
        counts.position_indices,
        counts.drawable_masks,
        counts.draw_order_groups,
        counts.draw_order_group_objects,
        counts.glue,
        counts.glue_info,
        counts.glue_keyforms,
        counts.keyform_multiply_colors,
        counts.keyform_screen_colors,
        counts.blend_shape_parameter_bindings,
        counts.blend_shape_keyform_bindings,
        counts.blend_shapes_warp_deformers,
        counts.blend_shapes_art_meshes,
        counts.blend_shape_constraint_indices,
        counts.blend_shape_constraints,
        counts.blend_shape_constraint_values,
        counts.blend_shapes_parts,
        counts.blend_shapes_rotation_deformers,
        counts.blend_shapes_glue,
        counts.offscreens,
        counts.offscreen_keyforms,
        counts.blend_shapes_offscreens,
    ];
    let target = version.count_info_ints() * 4;
    let mut bytes = Vec::with_capacity(target);
    for value in named {
        bytes.extend_from_slice(&i32::try_from(value).unwrap_or(0).to_le_bytes());
    }
    bytes.truncate(target);
    while bytes.len() < target {
        bytes.extend_from_slice(&0i32.to_le_bytes());
    }
    bytes
}

// ---------------------------------------------------------------------------
// Fixture definitions
// ---------------------------------------------------------------------------

/// Names of all valid synthetic fixtures, in deterministic order.
pub const FIXTURE_NAMES: &[&str] = &[
    "fixture-001-single-artmesh.moc3",
    "fixture-002-artmesh-param.moc3",
    "fixture-003-warp.moc3",
    "fixture-004-nested-warp.moc3",
    "fixture-005-rotation.moc3",
    "fixture-006-clipping-mask.moc3",
    "fixture-007-multi-params.moc3",
    "fixture-008-multi-textures.moc3",
    "fixture-009-v50.moc3",
    "fixture-010-v53.moc3",
    "fixture-011-v30.moc3",
    "fixture-012-v40.moc3",
    "fixture-013-glue.moc3",
    "hierarchy-001-part-artmesh.moc3",
    "hierarchy-002-part-warp-artmesh.moc3",
    "hierarchy-003-part-rotation-artmesh.moc3",
    "hierarchy-004-nested-warp.moc3",
    "hierarchy-005-warp-rotation-artmesh.moc3",
    "hierarchy-006-multiple-parts.moc3",
    "hierarchy-007-orphan-artmesh.moc3",
    "hierarchy-008-ambiguous-parent.moc3",
    "hierarchy-009-cycle.moc3",
    "hierarchy-010-part-mismatch.moc3",
    "hierarchy-011-deep.moc3",
    "hierarchy-012-large-flat.moc3",
    "hierarchy-013-scale.moc3",
    "hierarchy-014-self-parent.moc3",
];

/// Fixtures excluded from golden snapshot tests (multi-megabyte documents).
pub const GOLDEN_SKIP: &[&str] = &["hierarchy-011-deep.moc3", "hierarchy-013-scale.moc3"];

type Builder = (&'static str, fn() -> SyntheticModel);

fn builders() -> Vec<Builder> {
    vec![
        ("fixture-001-single-artmesh.moc3", fixture_001),
        ("fixture-002-artmesh-param.moc3", fixture_002),
        ("fixture-003-warp.moc3", fixture_003),
        ("fixture-004-nested-warp.moc3", fixture_004),
        ("fixture-005-rotation.moc3", fixture_005),
        ("fixture-006-clipping-mask.moc3", fixture_006),
        ("fixture-007-multi-params.moc3", fixture_007),
        ("fixture-008-multi-textures.moc3", fixture_008),
        ("fixture-009-v50.moc3", fixture_009),
        ("fixture-010-v53.moc3", fixture_010),
        ("fixture-011-v30.moc3", fixture_011),
        ("fixture-012-v40.moc3", fixture_012),
        ("fixture-013-glue.moc3", fixture_013),
        ("hierarchy-001-part-artmesh.moc3", hierarchy_001),
        ("hierarchy-002-part-warp-artmesh.moc3", hierarchy_002),
        ("hierarchy-003-part-rotation-artmesh.moc3", hierarchy_003),
        ("hierarchy-004-nested-warp.moc3", hierarchy_004),
        ("hierarchy-005-warp-rotation-artmesh.moc3", hierarchy_005),
        ("hierarchy-006-multiple-parts.moc3", hierarchy_006),
        ("hierarchy-007-orphan-artmesh.moc3", hierarchy_007),
        ("hierarchy-008-ambiguous-parent.moc3", hierarchy_008),
        ("hierarchy-009-cycle.moc3", hierarchy_009),
        ("hierarchy-010-part-mismatch.moc3", hierarchy_010),
        ("hierarchy-011-deep.moc3", hierarchy_011),
        ("hierarchy-012-large-flat.moc3", hierarchy_012),
        ("hierarchy-013-scale.moc3", hierarchy_013),
        ("hierarchy-014-self-parent.moc3", hierarchy_014),
    ]
}

/// Build all fixtures deterministically.
pub fn all_fixtures() -> Vec<Fixture> {
    builders()
        .into_iter()
        .map(|(name, builder)| {
            let model = builder();
            Fixture {
                name,
                bytes: build(&model),
            }
        })
        .collect()
}

/// Build one fixture by file name (for tests).
pub fn build_named(name: &str) -> Option<Vec<u8>> {
    builders()
        .into_iter()
        .find(|(fixture_name, _)| *fixture_name == name)
        .map(|(_, builder)| build(&builder()))
}

fn empty_binding() -> Vec<BindingSpec> {
    vec![BindingSpec { tables: Vec::new() }]
}

fn quad_mesh(name: &str, binding: usize) -> ArtMeshSpec {
    ArtMeshSpec::quad(name, binding)
}

fn simple_group(item_count: usize) -> Vec<DrawGroupSpec> {
    vec![DrawGroupSpec {
        items: (0..item_count)
            .map(|index| (0, i64::try_from(index).unwrap_or(0), -1))
            .collect(),
        max_order: 0,
        min_order: 0,
    }]
}

fn fixture_001() -> SyntheticModel {
    SyntheticModel {
        version: 2,
        canvas: CanvasSpec {
            y_reversed: true,
            ..CanvasSpec::default()
        },
        parameters: Vec::new(),
        bindings: empty_binding(),
        parts: Vec::new(),
        deformers: Vec::new(),
        art_meshes: vec![ArtMeshSpec {
            flags: 0x05, // additive blending + double sided
            ..quad_mesh("ArtMesh_Synthetic_00", 0)
        }],
        glues: Vec::new(),
        draw_groups: simple_group(1),
    }
}

fn fixture_002() -> SyntheticModel {
    SyntheticModel {
        version: 2,
        parameters: vec![ParamSpec::two_key("ParamSynthetic_AngleX")],
        bindings: vec![BindingSpec { tables: vec![0] }],
        parts: vec![PartSpec {
            name: "Part_Synthetic_00".to_string(),
            parent: None,
            binding: 0,
            visible: true,
            enabled: true,
        }],
        art_meshes: vec![ArtMeshSpec {
            parent_part: Some(0),
            ..quad_mesh("ArtMesh_Synthetic_00", 0)
        }],
        deformers: Vec::new(),
        draw_groups: simple_group(1),
        ..SyntheticModel::default()
    }
}

fn warp_deformer(
    name: &str,
    parent: Option<usize>,
    rows: u32,
    cols: u32,
    quad: bool,
) -> DeformerSpec {
    DeformerSpec {
        name: name.to_string(),
        kind: DeformerKind::Warp { rows, cols, quad },
        parent_part: None,
        parent_deformer: parent,
        binding: 0,
    }
}

fn fixture_003() -> SyntheticModel {
    SyntheticModel {
        version: 2,
        bindings: empty_binding(),
        deformers: vec![warp_deformer(
            "WarpDeformer_Synthetic_00",
            None,
            1,
            1,
            false,
        )],
        art_meshes: vec![ArtMeshSpec {
            parent_deformer: Some(0),
            ..quad_mesh("ArtMesh_Synthetic_00", 0)
        }],
        draw_groups: simple_group(1),
        ..SyntheticModel::default()
    }
}

fn fixture_004() -> SyntheticModel {
    SyntheticModel {
        version: 2,
        bindings: empty_binding(),
        deformers: vec![
            warp_deformer("WarpDeformer_Synthetic_00", None, 1, 1, false),
            warp_deformer("WarpDeformer_Synthetic_01", Some(0), 2, 2, false),
        ],
        art_meshes: vec![ArtMeshSpec {
            parent_deformer: Some(1),
            ..quad_mesh("ArtMesh_Synthetic_00", 0)
        }],
        draw_groups: simple_group(1),
        ..SyntheticModel::default()
    }
}

fn fixture_005() -> SyntheticModel {
    SyntheticModel {
        version: 2,
        bindings: empty_binding(),
        deformers: vec![DeformerSpec {
            name: "RotationDeformer_Synthetic_00".to_string(),
            kind: DeformerKind::Rotation { base_angle: 30.0 },
            parent_part: None,
            parent_deformer: None,
            binding: 0,
        }],
        art_meshes: vec![ArtMeshSpec {
            parent_deformer: Some(0),
            ..quad_mesh("ArtMesh_Synthetic_00", 0)
        }],
        draw_groups: simple_group(1),
        ..SyntheticModel::default()
    }
}

fn fixture_006() -> SyntheticModel {
    SyntheticModel {
        version: 2,
        bindings: empty_binding(),
        art_meshes: vec![
            quad_mesh("ArtMesh_Synthetic_00", 0),
            ArtMeshSpec {
                masks: vec![0],
                ..quad_mesh("ArtMesh_Synthetic_01", 0)
            },
        ],
        draw_groups: simple_group(2),
        ..SyntheticModel::default()
    }
}

fn fixture_007() -> SyntheticModel {
    SyntheticModel {
        version: 4,
        parameters: vec![
            ParamSpec::two_key("ParamSynthetic_A"),
            ParamSpec::two_key("ParamSynthetic_B"),
            ParamSpec::two_key("ParamSynthetic_C"),
            ParamSpec::two_key("ParamSynthetic_D"),
            ParamSpec::two_key("ParamSynthetic_E"),
        ],
        bindings: vec![
            BindingSpec { tables: vec![0, 1] },
            BindingSpec {
                tables: vec![2, 3, 4],
            },
            BindingSpec { tables: vec![0] },
            BindingSpec { tables: Vec::new() },
        ],
        parts: vec![
            PartSpec {
                name: "Part_Synthetic_00".to_string(),
                parent: None,
                binding: 0,
                visible: true,
                enabled: true,
            },
            PartSpec {
                name: "Part_Synthetic_01".to_string(),
                parent: Some(0),
                binding: 1,
                visible: true,
                enabled: true,
            },
        ],
        art_meshes: vec![
            ArtMeshSpec {
                parent_part: Some(0),
                ..quad_mesh("ArtMesh_Synthetic_00", 2)
            },
            ArtMeshSpec {
                parent_part: Some(1),
                ..quad_mesh("ArtMesh_Synthetic_01", 3)
            },
        ],
        deformers: Vec::new(),
        // Two groups: group 0 nests group 1 through a part item; group 1
        // holds both art meshes (exercises nested draw order groups).
        draw_groups: vec![
            DrawGroupSpec {
                items: vec![(1, 0, 1)],
                max_order: 0,
                min_order: 0,
            },
            DrawGroupSpec {
                items: vec![(0, 0, -1), (0, 1, -1)],
                max_order: 0,
                min_order: 0,
            },
        ],
        ..SyntheticModel::default()
    }
}

fn fixture_008() -> SyntheticModel {
    SyntheticModel {
        version: 4,
        parameters: vec![ParamSpec::two_key("ParamSynthetic_AngleX")],
        bindings: vec![BindingSpec { tables: vec![0] }],
        parts: vec![PartSpec {
            name: "Part_Synthetic_00".to_string(),
            parent: None,
            binding: 0,
            visible: true,
            enabled: true,
        }],
        art_meshes: vec![
            ArtMeshSpec {
                parent_part: Some(0),
                texture: 0,
                ..quad_mesh("ArtMesh_Synthetic_00", 0)
            },
            ArtMeshSpec {
                parent_part: Some(0),
                texture: 1,
                ..quad_mesh("ArtMesh_Synthetic_01", 0)
            },
        ],
        draw_groups: simple_group(2),
        ..SyntheticModel::default()
    }
}

fn fixture_009() -> SyntheticModel {
    SyntheticModel {
        version: 5,
        ..fixture_002()
    }
}

fn fixture_010() -> SyntheticModel {
    let mut model = fixture_002();
    model.version = 6;
    model
}

fn fixture_011() -> SyntheticModel {
    SyntheticModel {
        version: 1,
        ..fixture_002()
    }
}

fn fixture_012() -> SyntheticModel {
    let mut model = fixture_003();
    model.version = 3;
    if let Some(deformer) = model.deformers.get_mut(0) {
        if let DeformerKind::Warp { quad, .. } = &mut deformer.kind {
            *quad = true;
        }
    }
    model
}

fn fixture_013() -> SyntheticModel {
    SyntheticModel {
        version: 2,
        bindings: empty_binding(),
        art_meshes: vec![
            quad_mesh("ArtMesh_Synthetic_00", 0),
            quad_mesh("ArtMesh_Synthetic_01", 0),
        ],
        glues: vec![GlueSpec {
            name: "Glue_Synthetic_00".to_string(),
            art_mesh_a: 0,
            art_mesh_b: 1,
            binding: 0,
            info: vec![(0.5, 0), (0.5, 0), (1.0, 1), (1.0, 1)],
        }],
        draw_groups: simple_group(2),
        ..SyntheticModel::default()
    }
}

// ---------------------------------------------------------------------------
// Hierarchy fixtures (AGENT.3)
// ---------------------------------------------------------------------------

fn part_spec(name: &str, parent: Option<usize>, binding: usize) -> PartSpec {
    PartSpec {
        name: name.to_string(),
        parent,
        binding,
        visible: true,
        enabled: true,
    }
}

fn warp_spec(
    name: &str,
    parent_deformer: Option<usize>,
    parent_part: Option<usize>,
    binding: usize,
) -> DeformerSpec {
    DeformerSpec {
        name: name.to_string(),
        kind: DeformerKind::Warp {
            rows: 1,
            cols: 1,
            quad: false,
        },
        parent_part,
        parent_deformer,
        binding,
    }
}

fn rotation_spec(
    name: &str,
    parent_deformer: Option<usize>,
    parent_part: Option<usize>,
    binding: usize,
) -> DeformerSpec {
    DeformerSpec {
        name: name.to_string(),
        kind: DeformerKind::Rotation { base_angle: 0.0 },
        parent_part,
        parent_deformer,
        binding,
    }
}

fn mesh_spec(
    name: &str,
    parent_deformer: Option<usize>,
    parent_part: Option<usize>,
    binding: usize,
) -> ArtMeshSpec {
    ArtMeshSpec {
        parent_deformer,
        parent_part,
        ..ArtMeshSpec::quad(name, binding)
    }
}

fn hierarchy_001() -> SyntheticModel {
    SyntheticModel {
        version: 2,
        parts: vec![part_spec("Part_Synthetic_00", None, 0)],
        art_meshes: vec![mesh_spec("ArtMesh_Synthetic_00", None, Some(0), 0)],
        ..SyntheticModel::default()
    }
}

fn hierarchy_002() -> SyntheticModel {
    SyntheticModel {
        version: 2,
        parts: vec![part_spec("Part_Synthetic_00", None, 0)],
        deformers: vec![warp_spec("WarpDeformer_Synthetic_00", None, Some(0), 0)],
        art_meshes: vec![mesh_spec("ArtMesh_Synthetic_00", Some(0), Some(0), 0)],
        ..SyntheticModel::default()
    }
}

fn hierarchy_003() -> SyntheticModel {
    SyntheticModel {
        version: 2,
        parts: vec![part_spec("Part_Synthetic_00", None, 0)],
        deformers: vec![rotation_spec(
            "RotationDeformer_Synthetic_00",
            None,
            Some(0),
            0,
        )],
        art_meshes: vec![mesh_spec("ArtMesh_Synthetic_00", Some(0), Some(0), 0)],
        ..SyntheticModel::default()
    }
}

fn hierarchy_004() -> SyntheticModel {
    SyntheticModel {
        version: 2,
        parts: vec![part_spec("Part_Synthetic_00", None, 0)],
        deformers: vec![
            warp_spec("WarpDeformer_Synthetic_00", None, Some(0), 0),
            warp_spec("WarpDeformer_Synthetic_01", Some(0), None, 0),
        ],
        art_meshes: vec![mesh_spec("ArtMesh_Synthetic_00", Some(1), None, 0)],
        ..SyntheticModel::default()
    }
}

fn hierarchy_005() -> SyntheticModel {
    SyntheticModel {
        version: 2,
        parts: vec![part_spec("Part_Synthetic_00", None, 0)],
        deformers: vec![
            warp_spec("WarpDeformer_Synthetic_00", None, Some(0), 0),
            rotation_spec("RotationDeformer_Synthetic_00", Some(0), None, 0),
        ],
        art_meshes: vec![mesh_spec("ArtMesh_Synthetic_00", Some(1), None, 0)],
        ..SyntheticModel::default()
    }
}

fn hierarchy_006() -> SyntheticModel {
    SyntheticModel {
        version: 2,
        parts: vec![
            part_spec("Part_Synthetic_00", None, 0),
            part_spec("Part_Synthetic_01", Some(0), 0),
            part_spec("Part_Synthetic_02", Some(1), 0),
        ],
        art_meshes: vec![
            mesh_spec("ArtMesh_Synthetic_00", None, Some(0), 0),
            mesh_spec("ArtMesh_Synthetic_01", None, Some(1), 0),
            mesh_spec("ArtMesh_Synthetic_02", None, Some(2), 0),
        ],
        ..SyntheticModel::default()
    }
}

fn hierarchy_007() -> SyntheticModel {
    SyntheticModel {
        version: 2,
        parts: vec![part_spec("Part_Synthetic_00", None, 0)],
        art_meshes: vec![
            mesh_spec("ArtMesh_Synthetic_00", None, Some(0), 0),
            mesh_spec("ArtMesh_Orphan", None, None, 0),
        ],
        ..SyntheticModel::default()
    }
}

fn hierarchy_008() -> SyntheticModel {
    SyntheticModel {
        version: 2,
        parameters: vec![ParamSpec::two_key("ParamSynthetic_Shared")],
        bindings: vec![BindingSpec { tables: vec![0] }],
        parts: vec![
            part_spec("Part_Synthetic_00", None, 0),
            part_spec("Part_Synthetic_01", None, 0),
        ],
        art_meshes: vec![mesh_spec("ArtMesh_Orphan", None, None, 0)],
        ..SyntheticModel::default()
    }
}

fn hierarchy_009() -> SyntheticModel {
    SyntheticModel {
        version: 2,
        parts: vec![part_spec("Part_Synthetic_00", None, 0)],
        deformers: vec![
            warp_spec("WarpDeformer_Synthetic_00", Some(1), Some(0), 0),
            warp_spec("WarpDeformer_Synthetic_01", Some(0), None, 0),
        ],
        art_meshes: vec![mesh_spec("ArtMesh_Synthetic_00", Some(0), None, 0)],
        ..SyntheticModel::default()
    }
}

fn hierarchy_010() -> SyntheticModel {
    SyntheticModel {
        version: 2,
        parts: vec![
            part_spec("Part_Synthetic_00", None, 0),
            part_spec("Part_Synthetic_01", None, 0),
        ],
        deformers: vec![warp_spec("WarpDeformer_Synthetic_00", None, Some(0), 0)],
        art_meshes: vec![mesh_spec("ArtMesh_Synthetic_00", Some(0), None, 0)]
            .into_iter()
            .map(|mut mesh| {
                mesh.parent_part = Some(1);
                mesh
            })
            .collect(),
        ..SyntheticModel::default()
    }
}

fn hierarchy_011() -> SyntheticModel {
    let depth = 1500usize;
    let mut deformers = Vec::with_capacity(depth);
    for index in 0..depth {
        let parent = if index == 0 { None } else { Some(index - 1) };
        let parent_part = if index == 0 { Some(0) } else { None };
        deformers.push(warp_spec(
            &format!("WarpDeformer_{index:04}"),
            parent,
            parent_part,
            0,
        ));
    }
    SyntheticModel {
        version: 2,
        parts: vec![part_spec("Part_Synthetic_00", None, 0)],
        deformers,
        art_meshes: vec![mesh_spec("ArtMesh_Synthetic_00", Some(depth - 1), None, 0)],
        ..SyntheticModel::default()
    }
}

fn hierarchy_012() -> SyntheticModel {
    let mesh_count = 1500usize;
    let art_meshes = (0..mesh_count)
        .map(|index| mesh_spec(&format!("ArtMesh_{index:04}"), None, Some(0), 0))
        .collect();
    SyntheticModel {
        version: 2,
        parts: vec![part_spec("Part_Synthetic_00", None, 0)],
        art_meshes,
        ..SyntheticModel::default()
    }
}

fn hierarchy_013() -> SyntheticModel {
    let warp_count = 2000usize;
    let deformers = (0..warp_count)
        .map(|index| warp_spec(&format!("WarpDeformer_{index:04}"), None, Some(0), 0))
        .collect();
    let art_meshes = (0..warp_count * 2)
        .map(|index| mesh_spec(&format!("ArtMesh_{index:04}"), Some(index / 2), Some(0), 0))
        .collect();
    SyntheticModel {
        version: 2,
        parts: vec![part_spec("Part_Synthetic_00", None, 0)],
        deformers,
        art_meshes,
        ..SyntheticModel::default()
    }
}

fn hierarchy_014() -> SyntheticModel {
    SyntheticModel {
        version: 2,
        parts: vec![part_spec("Part_Synthetic_00", None, 0)],
        deformers: vec![warp_spec("WarpDeformer_Synthetic_00", Some(0), Some(0), 0)],
        art_meshes: vec![mesh_spec("ArtMesh_Synthetic_00", None, Some(0), 0)],
        ..SyntheticModel::default()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fixture_names_match_builders() {
        let names: Vec<&str> = builders().iter().map(|(name, _)| *name).collect();
        assert_eq!(names, FIXTURE_NAMES);
    }

    #[test]
    fn generation_is_deterministic() {
        for fixture in all_fixtures() {
            let again = build_named(fixture.name);
            assert_eq!(Some(fixture.bytes.clone()), again, "{}", fixture.name);
        }
    }

    #[test]
    fn fixtures_parse_with_the_inspector() {
        for fixture in all_fixtures() {
            let limits = moc3_ingest::Limits::default();
            let parsed = moc3_ingest::parse(&fixture.bytes, &limits);
            assert!(
                parsed.is_ok(),
                "{} failed: {:?}",
                fixture.name,
                parsed.err()
            );
        }
    }
}
